# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version="1804.02"
  config.vm.synced_folder "./scripts", "/vagrant", type: "rsync"

    config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = 256
     vb.cpus = 1
   end
  
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", path: "rename_vg.sh"
  #   apt-get install -y apache2
  
end
