---

- name: Configure assymetric routing
  hosts: router1
  become: yes
  tasks:

    - name: set up assynchronus routing
      sysctl: 
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        state: present

    - name: Set up OSPF
      template:
        src: frr.conf.cost.router1
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640

    - name: restart FRR
      service:
        name: frr
        state: restarted
        enabled: true