# -*- mode: ruby -*-
# vim: set ft=ruby :

#Описание ВМ
MACHINES = {
  :exc2vm => {
    :box_name => "borovikphone/centos7k6plain",
    :ip_addr => '192.168.56.101',
	  :disks => {
		  :sata1 => {
			  :dfile => './sata1.vdi',
			  :size => 1024,
			  :port => 1
		  },
		  :sata2 => {
        :dfile => './sata2.vdi',
        :size => 1024, 
			  :port => 2
		  },
      :sata3 => {
        :dfile => './sata3.vdi',
        :size => 1024,
        :port => 3
      },
      :sata4 => {
        :dfile => './sata4.vdi',
        :size => 1024, 
        :port => 4
      }

	  }
  },
}

#Основная часть
Vagrant.configure("2") do |config|

  config.vm.synced_folder "./scripts", "/vagrant", type: "rsync"

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        box.vm.network "private_network", ip: boxconfig[:ip_addr]

        box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1024"]
            needsController = false
		        boxconfig[:disks].each do |dname, dconf|
			      unless File.exist?(dconf[:dfile])
				    vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
            needsController =  true
        end
      end
                  
      if needsController == true
        vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          boxconfig[:disks].each do |dname, dconf|
          vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
        end
      end
    end
    

 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
  	  SHELL
      
      #Раскомментировать, чтобы собрать рэйд при запуске ВМ. Скрипт сборки должен быть в директории scripts с Vagrantfile. 
      #box.vm.provision :shell, :path=>"./scripts/_createraid0.sh"
    end
    
  end
end
