# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"

    config.vm.define "server" do |server|
        server.vm.hostname = "server"
        server.vm.network "private_network", ip: "192.168.56.10"
    end

    config.vm.define "client" do |client|
        client.vm.hostname = "client"
        client.vm.network "private_network", ip: "192.168.56.20"

        client.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/ConfigHost.yml"
            ansible.inventory_path = "playbooks/hosts"
            ansible.host_key_checking = "false"
            ansible.limit = "all"
        end
    end

end
    