# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :docker => {
        :box_name => "centos/7",
        :ip_addr => '192.168.56.150'
  }
}

Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", type: "rsync"

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo;
          yum install docker-ce docker-ce-cli containerd.io -y;
          systemctl start docker;
          systemctl enable docker
        SHELL
          


      end
  end
end