# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
 config.vm.box="centos/7"
 config.vm.box_version="2004.1"
 
 config.vm.provider "virtualbox" do |v|
  v.memory=256
  v.cpus=1
 end

 config.vm.define "makerepo" do |makerepo|
  makerepo.vm.network "private_network", ip:"192.168.56.10"
  makerepo.vm.hostname="makerepo"
  makerepo.vm.provision "shell", path: "make_rpm_repo.sh"
 end
end
