# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.synced_folder "./", "/vagrant", type: "rsync"
  config.vm.provider "virtualbox" do |v|
    v.memory=256
  end

  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.provision :shell, :path=>"./scripts/_InstallWeb.sh"
    web.vm.network "private_network", ip: "192.168.56.10"
    
  end

  config.vm.define "log" do |log|
    log.vm.hostname = "log"
    log.vm.network "private_network", ip: "192.168.56.15"
    log.vm.provision :shell, :path=> "./scripts/_InstallLog.sh"
  end

  
end
